"""AI Credit Copilot context building and question answering.

Answers are generated from the selected company-period's observed figures,
model output, and early-warning signals. The default responder is a
transparent, rule-based interpreter that calls no language model and no
network service. When a free OpenAI-compatible LLM endpoint is configured
(see ``msme_ews.llm``), answers are generated by that model instead, with
automatic fallback to the rule-based engine when the endpoint fails.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from typing import Any

import pandas as pd

from msme_ews.llm import (
    LLMSettings,
    SYSTEM_PROMPT,
    build_messages,
    chat_completion,
    context_prompt,
    dataset_context_prompt,
)

_FOLLOW_UP_PATTERN = re.compile(r"\b(it|that|this|those|these|they|also|and then|what about|how about)\b", re.I)
_COMPARISON_KEYWORDS = (
    "compare", "compared", "versus", " vs ", "last year", "previous period", "prior period",
    "last period", "trend", "getting worse", "getting better", "deteriorating", "improving",
)
_RELIABILITY_KEYWORDS = (
    "reliable", "reliability", "confident", "confidence", "trust", "accurate", "accuracy",
    "certain", "how good is", "quality of",
)
_MISSING_KEYWORDS = (
    "missing", "not available", "what data", "which data", "gaps", "incomplete", "unavailable",
)
_SENSITIVITY_KEYWORDS = (
    "what if", "impact", "sensitivity", "sensitive to", "if leverage", "if revenue", "if debt",
    "if liquidity", "if margin", "if cash flow", "effect of", "effect if",
)


def build_credit_context(
    frame: pd.DataFrame,
    selected: pd.DataFrame,
    selected_features: pd.DataFrame,
    flags: pd.DataFrame,
    row_index: int,
    result: dict,
) -> dict[str, Any]:
    """Collect everything the copilot is allowed to reason about."""
    row = selected.iloc[0].copy()
    feat = selected_features.iloc[0].copy()
    active_flags = list(flags.iloc[row_index][flags.iloc[row_index]].index)
    company_id = row.get("company_id", "Selected company")
    def observed_number(name: str) -> float | None:
        value = pd.to_numeric(pd.Series([feat.get(name)]), errors="coerce").iloc[0]
        return float(value) if pd.notna(value) else None

    revenue = observed_number("Revenue")
    profit = observed_number("Net_Profit")
    current_ratio = observed_number("Current_Ratio")
    leverage = observed_number("Debt_to_Assets")
    margin = observed_number("EBITDA_Margin")
    coverage = observed_number("Interest_Coverage")
    cash_flow = observed_number("Cash_Flow_Operations")
    probability = result.get("distress_probability")
    health_score = result.get("health_score")
    history_available = bool("company_id" in frame.columns and "period" in frame.columns)
    return {
        "company": company_id,
        "period": row.get("period", "latest identified period"),
        "revenue": revenue,
        "revenue_growth": observed_number("Sales_Growth"),
        "profit": profit,
        "current_ratio": current_ratio,
        "debt_to_assets": leverage,
        "ebitda_margin": margin,
        "interest_coverage": coverage,
        "cash_flow_operations": cash_flow,
        "default_probability": float(probability) if probability is not None else None,
        "risk_index": result.get("risk_index"),
        "health_score": health_score,
        "risk_category": result["risk_category"],
        "assessment_method": result.get("method", "Existing ML model"),
        "coverage_label": result.get("coverage_label", "Coverage not available"),
        "coverage_percent": result.get("coverage_percent"),
        "warnings": active_flags,
        "top_risk": result.get("top_risk_factors", []),
        "protective": result.get("protective_factors", []),
        "history_available": history_available,
        "prior_period": _prior_period_summary(frame, row_index),
    }


def _prior_period_summary(frame: pd.DataFrame, row_index: int) -> dict[str, Any] | None:
    """Locate the previous company-period so comparisons use observed history."""
    if "company_id" not in frame.columns or "period" not in frame.columns:
        return None
    current = frame.iloc[row_index]
    company = str(current.get("company_id"))
    history = frame.loc[frame["company_id"].astype(str) == company].copy()
    if len(history) < 2:
        return None
    history["_parsed_period"] = pd.to_datetime(history["period"], errors="coerce")
    history["_position"] = range(len(history))
    history = history.sort_values(["_parsed_period", "_position"])
    if current.name not in history.index:
        return None
    position = int(history.index.get_indexer([current.name])[0])
    if position == 0:
        return None
    previous_row = history.iloc[position - 1]
    features = pd.to_numeric(history["Revenue"], errors="coerce")
    return {
        "period": str(previous_row.get("period")),
        "revenue": None if pd.isna(previous_row.get("Revenue")) else float(previous_row.get("Revenue")),
        "revenue_change": (
            None if pd.isna(features.iloc[position]) or not features.iloc[position - 1]
            else float((features.iloc[position] - features.iloc[position - 1]) / abs(features.iloc[position - 1]))
        ),
    }


def resolve_question(question: str, history: Sequence[str] = ()) -> str:
    """Expand a short follow-up so it keeps the earlier question's subject."""
    text = (question or "").strip()
    if not text:
        return "summarize the financial health"
    if history and len(text) < 45 and _FOLLOW_UP_PATTERN.search(text):
        previous = str(history[-1]).strip()
        if previous and previous.lower() != text.lower():
            return f"{previous.rstrip('?.!')}? {text}"
    return text


def suggested_questions(context: dict[str, Any]) -> list[str]:
    """Context-aware prompt chips for the copilot input."""
    company = context.get("company", "this company")
    category = str(context.get("risk_category", "risk"))
    rule_based = context.get("assessment_method") != "Existing ML model"
    questions = [
        f"Why is {company} currently {category.lower()}?",
        "Summarize the financial health",
        "How reliable is this assessment?",
        "Which financial fields are missing?",
        "What are the biggest risk factors?",
        "Which strengths offset the risk?",
        "What could increase credit risk?",
        "What should management improve first?",
    ]
    if context.get("history_available") and context.get("prior_period"):
        questions.append("How does this compare with the previous period?")
    questions.append("What if revenue falls by 20%?")
    if rule_based:
        questions = [q for q in questions if "shap" not in q.lower()]
    return questions[:9]


def _reliability_answer(context: dict[str, Any]) -> str:
    method = context.get("assessment_method", "Existing ML model")
    coverage = context.get("coverage_label", "Coverage not available")
    confidence = context.get("coverage_percent")
    base = (
        f"The assessment is an analytical research estimate, not a guaranteed outcome. "
        f"Data coverage for this record is {coverage}."
    )
    if method != "Existing ML model":
        return (
            f"{base} No dataset-specific ML model is applied to this upload. The displayed score "
            "is a transparent heuristic rule-based index, not a calibrated probability of default. "
            "Supervised hold-out metrics are available only when a usable target is present."
        )
    return (
        f"{base} The score is the model's own output, and the confidence figure shown on the "
        "Risk Prediction page is only the distance from the decision midpoint, not calibrated "
        "uncertainty. Validate performance on representative future periods before operational use."
    )


def _missing_answer(context: dict[str, Any]) -> str:
    coverage = context.get("coverage_label", "Coverage not available")
    ratio = context.get("current_ratio")
    if pd.isna(ratio):
        return (
            f"Core-field coverage is {coverage}. Liquidity, leverage, margin, and coverage ratios "
            "could not be calculated because their inputs were not observed in this record, "
            "so those areas are unassessed rather than healthy."
        )
    return (
        f"Core-field coverage is {coverage}. Where a ratio is shown as not available, the "
        "underlying field was missing or its denominator was zero; missing values are never "
        "treated as healthy. Add the missing statement lines to widen the assessment."
    )


def _comparison_answer(context: dict[str, Any]) -> str:
    prior = context.get("prior_period")
    if not prior:
        return (
            "There is not an earlier dated company-period in this dataset, so no like-for-like "
            "comparison is possible. Add company and period columns covering multiple periods to "
            "enable trend and period-over-period comparison."
        )
    revenue_change = prior.get("revenue_change")
    movement = (
        f" Revenue is {revenue_change:+.1%} against the previous period."
        if revenue_change is not None
        else " A revenue change could not be calculated from the available rows."
    )
    risk_index = context.get("risk_index")
    risk_text = (
        f"{risk_index:.1f}/100 rule index"
        if risk_index is not None
        else "no calculable risk index"
    )
    return (
        f"The previous recorded period is {prior['period']}.{movement} "
        f"The current assessment is {context['risk_category']} with "
        f"{risk_text}, "
        "and the active early-warning signals are "
        f"{', '.join(context['warnings']) if context['warnings'] else 'none'}. "
        "Period-over-period movement in leverage, liquidity, and margins is the more reliable "
        "signal than a single-period snapshot."
    )


def _sensitivity_answer(context: dict[str, Any]) -> str:
    if context.get("assessment_method") != "Existing ML model":
        leverage = context.get("debt_to_assets")
        liquidity = context.get("current_ratio")
        drivers = [
            name
            for name, value, threshold, comparison in (
                ("leverage", leverage, 0.65, ">="),
                ("liquidity", liquidity, 1.0, "<"),
                ("operating margin", context.get("ebitda_margin"), 0.0, "<"),
                ("operating cash flow", context.get("cash_flow_operations"), 0.0, "<"),
            )
            if value is not None and not pd.isna(value)
            and ((value >= threshold) if comparison == ">=" else (value < threshold))
        ]
        evidence = (
            "Observed threshold signals: " + ", ".join(drivers) + ". "
            if drivers
            else "No measured threshold breach is available from the current fields. "
        )
        return (
            evidence
            + "Use Scenario Simulator to change revenue, margin, or debt. It recalculates the "
            "uploaded record's financial values and transparent rule-based index; it does not "
            "produce an unsupported ML prediction."
        )
    leverage = context.get("debt_to_assets", 0.0)
    liquidity = context.get("current_ratio")
    drivers = [
        name
        for name, value, threshold, comparison in (
            ("leverage", leverage, 0.65, ">="),
            ("liquidity", liquidity, 1.0, "<"),
            ("operating margin", context.get("ebitda_margin", 0.0), 0.0, "<"),
            ("operating cash flow", context.get("cash_flow_operations", 0.0), 0.0, "<"),
        )
        if value is not None and not pd.isna(value)
        and ((value >= threshold) if comparison == ">=" else (value < threshold))
    ]
    if not drivers:
        drivers = ["revenue level", "operating cash generation"]
    return (
        f"This assessment is most sensitive to {', '.join(drivers)}. "
        "Use the Scenario Simulator to apply an explicit revenue, margin, or debt change and read "
        "the recalculated risk index rather than a verbal estimate."
    )


def _probability_text(context: dict[str, Any]) -> str:
    probability = context.get("default_probability")
    return f"{probability:.1%}" if probability is not None else "an unavailable"


def generate_credit_copilot_response(
    question: str,
    context: dict[str, Any],
    history: Sequence[str] = (),
) -> str:
    """Answer a copilot question from the observed figures for one company-period."""
    q = resolve_question(question, history).lower()
    warnings = context["warnings"]
    risk_prob = context["default_probability"]
    current_ratio = context["current_ratio"]
    leverage = context["debt_to_assets"]
    margin = context["ebitda_margin"]
    cash_flow = context["cash_flow_operations"]
    revenue = context["revenue"]
    profit = context["profit"]

    if not q:
        q = "summarize the financial health"

    if any(keyword in q for keyword in _RELIABILITY_KEYWORDS):
        return _reliability_answer(context)

    if any(keyword in q for keyword in _MISSING_KEYWORDS):
        return _missing_answer(context)

    if any(keyword in q for keyword in _SENSITIVITY_KEYWORDS):
        return _sensitivity_answer(context)

    if any(keyword in q for keyword in _COMPARISON_KEYWORDS):
        return _comparison_answer(context)

    if context.get("assessment_method") != "Existing ML model":
        drivers = [
            str(item.get("feature", ""))
            for item in context.get("top_risk", [])
            if item.get("feature")
        ]
        risk_index = context.get("risk_index")
        if any(keyword in q for keyword in ("missing", "unavailable", "coverage", "data quality")):
            return (
                f"Observed core-field coverage is {context['coverage_label']}. Missing inputs are "
                "unassessed rather than treated as zero or healthy."
            )
        if any(keyword in q for keyword in ("warning", "signal", "early")):
            return (
                "Active warning signals from the selected uploaded record: "
                + (", ".join(warnings) if warnings else "none of the configured rules triggered.")
            )
        if any(keyword in q for keyword in ("strength", "healthy", "positive")):
            strengths = [
                label for label, value, threshold, comparison in (
                    ("positive revenue growth", context.get("revenue_growth"), 0, "gt"),
                    ("current ratio at or above 1.0x", current_ratio, 1, "ge"),
                    ("positive operating cash flow", cash_flow, 0, "gt"),
                    ("positive net profit", profit, 0, "gt"),
                )
                if value is not None and (
                    (comparison == "gt" and value > threshold)
                    or (comparison == "ge" and value >= threshold)
                )
            ]
            return (
                "Observed strengths in the selected upload: "
                + (", ".join(strengths) if strengths else "none can be confirmed from the available fields.")
            )
        if any(keyword in q for keyword in ("improve", "recommend", "action", "management")):
            actions = []
            if "Negative operating cash flow" in warnings or (cash_flow is not None and cash_flow < 0):
                actions.append("review working-capital conversion and cash collection")
            if "Increasing leverage" in warnings or (leverage is not None and leverage >= 0.65):
                actions.append("verify debt capacity and maturity exposure")
            if "Falling liquidity" in warnings or (current_ratio is not None and current_ratio < 1):
                actions.append("review short-term liquidity and obligations")
            if "Deteriorating margins" in warnings or (margin is not None and margin < 0):
                actions.append("investigate cost drivers and margin pressure")
            return (
                "Based on observed signals, prioritize "
                + ("; ".join(actions) if actions else "continued monitoring of the uploaded financial fields")
                + "."
            )
        if any(keyword in q for keyword in ("why", "risk", "risky", "factor")):
            details = [*drivers, *warnings]
            index_text = (
                f"{float(risk_index):.1f}/100 rule index"
                if risk_index is not None
                else "no calculable rule index due to limited observed fields"
            )
            return (
                f"The selected record is classified {context['risk_category']} with {index_text}. "
                "Observed drivers/signals: "
                + (", ".join(details[:5]) if details else "no configured adverse condition was triggered.")
                + " This is a transparent heuristic, not a default probability."
            )
        if any(keyword in q for keyword in ("summarize", "summary", "financial health")):
            values = []
            for label, value, suffix in (
                ("Revenue", revenue, ""),
                ("Net profit", profit, ""),
                ("Current ratio", current_ratio, "x"),
                ("Debt/assets", leverage, ""),
                ("Operating cash flow", cash_flow, ""),
            ):
                values.append(
                    f"{label}: {value:,.4g}{suffix}" if value is not None else f"{label}: not available"
                )
            index_text = (
                f"{float(risk_index):.1f}/100"
                if risk_index is not None else "not available"
            )
            return (
                f"The active upload's selected record is {context['risk_category']} with a "
                f"rule-based risk index of {index_text}. " + "; ".join(values)
                + f". Core-field coverage: {context['coverage_label']}. "
                "The index is not a calibrated probability of default."
            )
        return (
            f"Analysis is based on the selected uploaded record ({context['coverage_label']}). "
            "Ask about its risk drivers, warnings, data coverage, or observed financial measures."
        )

    if any(keyword in q for keyword in ["why", "risky", "risk", "risk factors", "biggest risk"]):
        reasons = []
        if pd.notna(current_ratio) and current_ratio < 1.0:
            reasons.append(f"liquidity is thin at {current_ratio:.2f}x")
        if leverage >= 0.65:
            reasons.append(f"debt loads are elevated at {leverage:.2f} debt-to-assets")
        if margin < 0 or cash_flow < 0:
            reasons.append("operating margin and cash generation are under pressure")
        if warnings:
            reasons.append("early-warning flags such as " + ", ".join(warnings[:3]))
        if not reasons:
            reasons.append("the model is pricing in a moderate probability of distress across revenue, leverage, and margin signals")
        return (
            f"{context['company']} is considered risky because " + "; ".join(reasons) + ". "
            f"The current risk estimate sits at {risk_prob:.1%}, and the model is particularly sensitive to leverage, liquidity, and operating cash generation."
        )

    if any(keyword in q for keyword in ["shap", "feature importance", "factors", "top risk"]):
        top_risk = context["top_risk"][:3] if context.get("top_risk") else ["Revenue pressure", "Leverage strain", "Liquidity deterioration"]
        return (
            f"The largest contributors to the distress score are {', '.join(str(item) for item in top_risk[:3])}. "
            "In practice, elevated leverage, weaker liquidity, and pressure on profitability are the strongest drivers of the current model output."
        )

    if any(keyword in q for keyword in ["credit", "lend", "considered for credit", "should this company"]):
        if risk_prob < 0.25 and current_ratio > 1.0 and cash_flow >= 0:
            return f"Based on current signals, {context['company']} appears broadly creditworthy for a cautious structure: distress probability is {risk_prob:.1%}, cash flow is positive, and liquidity remains above 1.0x."
        return f"This company should be treated cautiously. With a {risk_prob:.1%} distress probability and several active warning signals, underwriting should require tighter covenants, collateral review, or a lower exposure limit."

    if any(keyword in q for keyword in ["weakness", "weakest", "financial weaknesses"]):
        weaknesses = []
        if pd.notna(current_ratio) and current_ratio < 1.0:
            weaknesses.append(f"liquidity is weak at {current_ratio:.2f}x")
        if leverage >= 0.65:
            weaknesses.append(f"leverage is elevated at {leverage:.2f} debt-to-assets")
        if margin < 0 or cash_flow < 0:
            weaknesses.append("operating margin and cash generation are deteriorating")
        if not weaknesses:
            weaknesses.append("operating resilience is uneven despite an otherwise stable revenue base")
        return f"The main weaknesses are {', '.join(weaknesses)}. These are the items most likely to pressure repayment capacity if conditions worsen."

    if any(keyword in q for keyword in ["strength", "strengths", "what are the strengths", "healthy"]):
        strengths = []
        if revenue > 0:
            strengths.append(f"revenue base remains at {revenue:,.0f}")
        if profit > 0:
            strengths.append(f"net profit remains positive at {profit:,.0f}")
        if current_ratio > 1.0:
            strengths.append(f"liquidity remains above 1.0x at {current_ratio:.2f}x")
        if not strengths:
            strengths.append("the model still sees some positive operating characteristics even under moderate risk")
        return f"The main strengths are {', '.join(strengths)}. Those fundamentals help offset the risk profile, but they are not yet strong enough to eliminate the monitoring need."

    if any(keyword in q for keyword in ["management improve", "improve", "should management"]):
        actions = [
            "tighten working-capital discipline and reduce receivable days",
            "lower dependency on debt-funded growth and improve debt service capacity",
            "improve operating cash conversion to sustain repayment capability",
        ]
        return f"Management should prioritize {', '.join(actions)}. These steps would strengthen liquidity, reduce leverage pressure, and improve the credit standing most quickly."

    if any(keyword in q for keyword in ["increase risk", "what could cause", "credit risk to increase", "cause risk"]):
        return (
            "The risk would rise if revenue contracts materially, operating cash flow turns negative, debt builds further, "
            "or liquidity slips below 1.0x. In this scenario, the model would likely move toward a higher default probability."
        )

    if any(keyword in q for keyword in ["summarize", "summary", "financial health"]):
        health = context.get("health_score")
        health_text = f" a health score of {health:.0f}/100" if health is not None else " no health score"
        return (
            f"{context['company']} is currently assessed as {context['risk_category']} with a {_probability_text(context)} distress probability and{health_text}. "
            f"Revenue is {revenue:,.0f}, net profit is {profit:,.0f}, liquidity is {current_ratio:.2f}x, and leverage is {leverage:.2f} debt-to-assets. "
            f"The main watchpoints are {', '.join(warnings[:3]) if warnings else 'limited but active risk factors'} ."
        )

    if any(keyword in q for keyword in ["early warning", "warning signals", "signals"]):
        return (
            f"The early-warning flags currently active are: {', '.join(warnings) if warnings else 'none at the current period'}. "
            "These are designed to highlight deteriorating liquidity, leverage drift, weak margins, and negative cash generation before distress becomes more visible."
        )

    if any(keyword in q for keyword in ["revenue falls", "20%", "fall by 20", "if revenue falls"]):
        adjusted_revenue = revenue * 0.8
        return (
            f"If revenue were to fall by 20%, the company would likely see a weaker margin profile and reduced cash conversion. "
            f"At an adjusted revenue level of {adjusted_revenue:,.0f}, the risk profile would likely move toward higher distress because leverage and fixed-cost pressure would become more visible."
        )

    return (
        f"{context['company']} currently shows a {context['risk_category']} profile with a {_probability_text(context)} distress probability. "
        "Liquidity, leverage, and operating cash flow are the key variables shaping the assessment, and the most immediate actions are to improve margin resilience and funding stability."
    )


def generate_credit_copilot_answer(
    question: str,
    context: dict[str, Any],
    history: Sequence[str] = (),
    llm: LLMSettings | None = None,
) -> tuple[str, str]:
    """Answer with the configured LLM, falling back to the rule engine.

    Returns ``(answer, source)`` where source is ``"llm"`` or
    ``"rule-based"``. Any endpoint failure (unreachable, timeout, empty
    answer) silently falls back so the copilot never breaks.
    """
    if llm is not None and llm.enabled:
        try:
            messages = build_messages(question, context_prompt(context), list(history))
            return chat_completion(messages, llm), "llm"
        except Exception:
            pass
    return generate_credit_copilot_response(question, context, history), "rule-based"


def generate_dataset_copilot_response(
    question: str,
    analysis: dict[str, Any],
) -> str:
    """Answer dataset questions deterministically from the currently analyzed upload."""
    data = analysis["data"]
    text = (question or "").strip()
    lowered = text.casefold()
    if not text:
        return "Enter a question about the currently analyzed dataset."

    for column in data.columns:
        if str(column).casefold() in lowered:
            series = data[column]
            missing = int(series.isna().sum())
            if str(column) in analysis["numeric_columns"]:
                values = pd.to_numeric(series, errors="coerce").dropna()
                if values.empty:
                    return f"'{column}' has no usable numeric values in the uploaded dataset."
                return (
                    f"From the active upload, '{column}' has {len(values):,} numeric values "
                    f"and {missing:,} missing records. Mean: {values.mean():,.4g}; "
                    f"median: {values.median():,.4g}; range: {values.min():,.4g} to "
                    f"{values.max():,.4g}."
                )
            counts = series.astype("string").fillna("Missing").value_counts().head(5)
            distribution = ", ".join(f"{label}: {count:,}" for label, count in counts.items())
            return (
                f"From the active upload, '{column}' has {series.nunique(dropna=True):,} "
                f"distinct observed values and {missing:,} missing records. Most common: "
                f"{distribution or 'no observed values'}."
            )

    if any(word in lowered for word in ("missing", "quality", "complete", "incomplete")):
        profile = analysis["profile"].sort_values("Missing %", ascending=False)
        fields = [
            f"{row['Variable']}: {row['Missing %']:.1f}%"
            for _, row in profile.loc[profile["Missing"] > 0].head(5).iterrows()
        ]
        return (
            f"The active upload has {analysis['missing_percent']:.1f}% missing cells and "
            f"{analysis['duplicate_count']:,} duplicate rows. Highest missingness: "
            + (", ".join(fields) if fields else "none; every profiled field is populated.")
        )
    if any(word in lowered for word in ("trend", "declin", "growth", "change over time")):
        trends = analysis["trends"]
        if trends.empty:
            return "No usable date-based trend was found in the active upload."
        return "Observed trends in the active upload: " + "; ".join(
            f"{row['Variable']} {str(row['Direction']).lower()}"
            + (
                f" ({row['Change %']:.1f}% from {row['From']} to {row['To']})"
                if pd.notna(row["Change %"]) else ""
            )
            for _, row in trends.head(6).iterrows()
        ) + "."
    if any(word in lowered for word in ("risk", "warning", "anomal", "outlier")):
        details = analysis.get("warning_details", [])
        if details:
            return "Data-derived signals in the active upload: " + " ".join(
                f"{item['Severity']}: {item['Evidence']} Reason: {item['Reason']}"
                for item in details[:5]
            )
        return (
            f"No structured warning was triggered in the active upload. Isolation Forest "
            f"flagged {analysis['anomaly_count']:,} of {analysis['anomaly_rows_scored']:,} "
            "scored rows as unusual."
        )
    if any(word in lowered for word in ("relationship", "correlation", "related")):
        correlations = analysis["correlations"]
        if correlations.empty:
            return "At least two varying numeric fields are needed to calculate relationships in this upload."
        return "Strongest observed numeric associations: " + "; ".join(
            f"{row['Variable A']} and {row['Variable B']} "
            f"(absolute correlation {row['Absolute correlation']:.2f})"
            for _, row in correlations.head(5).iterrows()
        ) + ". These are associations, not evidence of causation."
    if any(word in lowered for word in ("recommend", "action", "next step")):
        return "Recommendations based on the active upload: " + " ".join(
            analysis["recommendations"][:5]
        )
    if any(word in lowered for word in ("model", "target", "prediction", "predict")):
        model = analysis["model"]
        if model.get("status") == "evaluated":
            metrics = ", ".join(
                f"{name.replace('_', ' ')} {value:.3f}"
                for name, value in model.items()
                if name in {"accuracy", "balanced_accuracy", "mae", "r2"}
            )
            return (
                f"The active upload's target is '{model['target']}'. An exploratory "
                f"{model['model']} hold-out evaluation used {model['test_rows']:,} test rows "
                f"({metrics}). This is not calibrated and does not provide default probabilities."
            )
        return (
            "No usable target was detected in the active upload, so no supervised model "
            "prediction is available. Statistical patterns and anomalies are shown instead."
        )
    return str(analysis["executive_summary"])


def generate_dataset_copilot_answer(
    question: str,
    analysis: dict[str, Any],
    llm: LLMSettings | None = None,
) -> tuple[str, str]:
    """Answer a dataset question with the LLM, falling back to rules.

    Returns ``(answer, source)`` where source is ``"llm"`` or
    ``"rule-based"``. Only compact dataset metadata is sent to the
    endpoint, never the uploaded rows themselves.
    """
    if llm is not None and llm.enabled:
        try:
            messages = [
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": (
                        "Dataset profile context:\n"
                        f"{dataset_context_prompt(analysis)}\n\n"
                        f"Question: {question}\n\n"
                        "Answer concisely using only the context figures."
                    ),
                },
            ]
            return chat_completion(messages, llm), "llm"
        except Exception:
            pass
    return generate_dataset_copilot_response(question, analysis), "rule-based"
