"""Optional free LLM endpoint for the AI Copilot.

The copilot works with no configuration: answers come from the transparent
rule-based engine. When an OpenAI-compatible chat-completions endpoint is
configured, answers are generated by that model instead, with automatic
fallback to the rule-based engine if the endpoint is unreachable.

Free options:
- Ollama (local, no key, data never leaves the machine):
  ``LLM_API_BASE=http://localhost:11434/v1`` and ``LLM_MODEL=llama3.2``
- Groq free tier: ``LLM_API_BASE=https://api.groq.com/openai/v1`` plus
  ``LLM_API_KEY`` and a free model such as ``llama-3.3-70b-versatile``
- OpenRouter free models: ``LLM_API_BASE=https://openrouter.ai/api/v1``
  plus ``LLM_API_KEY`` and a ``:free`` model

Configuration is read from Streamlit secrets (``.streamlit/secrets.toml``)
and then environment variables. Only the derived credit context for the
selected record is sent to the endpoint, never the whole upload.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Any
from urllib.error import URLError
from urllib.request import Request, urlopen

DEFAULT_TIMEOUT = 30.0
DEFAULT_MODEL = "llama3.2"


@dataclass(frozen=True)
class LLMSettings:
    """Connection settings for an OpenAI-compatible chat endpoint."""

    api_base: str | None = None
    api_key: str | None = None
    model: str = DEFAULT_MODEL
    timeout: float = DEFAULT_TIMEOUT

    @property
    def enabled(self) -> bool:
        """True when an endpoint base URL is configured."""
        return bool(self.api_base)

    @property
    def label(self) -> str:
        """Human-readable model label for UI badges."""
        if not self.enabled:
            return "rule-based engine"
        base = str(self.api_base)
        if "localhost" in base or "127.0.0.1" in base:
            origin = "local model"
        else:
            origin = base.split("//", 1)[-1].split("/")[0]
        return f"AI model {self.model} ({origin})"


def _streamlit_secret(key: str) -> str | None:
    """Read a setting from Streamlit secrets when a runtime context exists."""
    try:
        import streamlit as st

        value = st.secrets.get(key)
        return str(value) if value else None
    except Exception:
        return None


def load_settings(environ: dict[str, str] | None = None) -> LLMSettings:
    """Load LLM settings from Streamlit secrets, then environment variables."""
    env = os.environ if environ is None else environ

    def setting(key: str) -> str | None:
        return _streamlit_secret(key) or env.get(key) or None

    timeout = DEFAULT_TIMEOUT
    raw_timeout = setting("LLM_TIMEOUT")
    if raw_timeout:
        try:
            timeout = max(1.0, float(raw_timeout))
        except ValueError:
            timeout = DEFAULT_TIMEOUT
    return LLMSettings(
        api_base=setting("LLM_API_BASE"),
        api_key=setting("LLM_API_KEY"),
        model=setting("LLM_MODEL") or DEFAULT_MODEL,
        timeout=timeout,
    )


def _format_value(value: Any) -> str:
    if value is None:
        return "not available"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, float):
        return f"{value:.6g}"
    if isinstance(value, list):
        return ", ".join(_format_value(item) for item in value) if value else "none"
    return str(value)


def context_prompt(context: dict[str, Any]) -> str:
    """Render the derived credit context as compact text for the model."""
    lines = []
    for key, value in context.items():
        if key in {"top_risk", "protective"}:
            items = [
                str(item.get("feature", item)) if isinstance(item, dict) else str(item)
                for item in (value or [])
            ]
            value = ", ".join(items) if items else "none"
        elif key == "warnings":
            value = ", ".join(str(warning) for warning in value) if value else "none"
        elif key == "prior_period" and isinstance(value, dict):
            value = "; ".join(f"{name} {_format_value(item)}" for name, item in value.items())
        lines.append(f"{key}: {_format_value(value)}")
    return "\n".join(lines)


def dataset_context_prompt(analysis: dict[str, Any]) -> str:
    """Render compact dataset-profile metadata for the model."""
    data = analysis.get("data")
    rows = len(data) if data is not None else 0
    columns = list(data.columns) if data is not None else []
    lines = [
        f"dataset rows: {rows:,}",
        f"dataset columns: {len(columns)}",
        f"numeric columns: {', '.join(map(str, analysis.get('numeric_columns', [])[:20])) or 'none'}",
        f"categorical columns: {', '.join(map(str, analysis.get('categorical_columns', [])[:20])) or 'none'}",
        f"missing cells: {analysis.get('missing_percent', 0.0):.1f}%",
        f"duplicate rows: {analysis.get('duplicate_count', 0):,}",
        f"anomalies flagged: {analysis.get('anomaly_count', 0):,}",
        f"analysis mode: {analysis.get('analysis_mode', 'not available')}",
        f"executive summary: {analysis.get('executive_summary', 'not available')}",
    ]
    if analysis.get("targets"):
        lines.append(f"detected targets: {', '.join(map(str, analysis['targets'][:5]))}")
    recommendations = analysis.get("recommendations") or []
    if recommendations:
        lines.append("recommendations: " + " | ".join(str(item) for item in recommendations[:5]))
    trends = analysis.get("trends")
    if trends is not None and not trends.empty:
        lines.append(f"observed trends: {len(trends)} trend rows")
    return "\n".join(lines)


SYSTEM_PROMPT = (
    "You are an MSME credit-risk analyst assistant. Answer only from the "
    "observed figures and signals provided in the context. Never invent "
    "numbers; if a figure is not provided, say it is not available. State "
    "clearly that outputs are analytical research estimates, not lending "
    "decisions, guarantees, or calibrated probabilities of default."
)


def build_messages(
    question: str,
    context_text: str,
    history: tuple[str, ...] | list[str] = (),
) -> list[dict[str, str]]:
    """Build the OpenAI chat-completions message list for a copilot question."""
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    for previous in list(history)[-4:]:
        messages.append({"role": "user", "content": f"Earlier question: {previous}"})
    messages.append({
        "role": "user",
        "content": (
            "Credit context (observed figures and signals for one company-period):\n"
            f"{context_text}\n\nQuestion: {question}\n\n"
            "Answer concisely using only the context figures."
        ),
    })
    return messages


def chat_completion(messages: list[dict[str, str]], settings: LLMSettings) -> str:
    """Call an OpenAI-compatible chat-completions endpoint and return the text."""
    if not settings.enabled:
        raise RuntimeError("No LLM endpoint is configured.")
    payload = json.dumps({
        "model": settings.model,
        "messages": messages,
        "temperature": 0.2,
        "max_tokens": 600,
    }).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if settings.api_key:
        headers["Authorization"] = f"Bearer {settings.api_key}"
    url = str(settings.api_base).rstrip("/") + "/chat/completions"
    request = Request(url, data=payload, headers=headers, method="POST")
    try:
        with urlopen(request, timeout=settings.timeout) as response:
            body = json.loads(response.read().decode("utf-8"))
    except URLError as error:
        raise RuntimeError(f"LLM endpoint unreachable: {error}") from error
    choices = body.get("choices") or []
    if not choices:
        raise RuntimeError("The LLM endpoint returned no choices.")
    text = (choices[0].get("message") or {}).get("content")
    if not text:
        raise RuntimeError("The LLM endpoint returned an empty answer.")
    return str(text).strip()
